use crate::shapes::enums::LanguageEnum;
use once_cell::sync::{Lazy, OnceCell};
use std::collections::HashMap;
use std::sync::RwLock;

pub struct Labels {
    pub could_not_recognize_home_directory: &'static str,
    pub could_not_create_app_directory: &'static str,
    pub could_not_create_team_directory: &'static str,
    pub new_match: &'static str,
    pub navigate: &'static str,
    pub confirm: &'static str,
    pub back: &'static str,
    pub quit: &'static str,
    pub home: &'static str,
    pub opponent: &'static str,
    pub date: &'static str,
    pub opponent_cannot_be_empty: &'static str,
    pub could_not_create_match: &'static str,
    pub invalid_date: &'static str,
    pub name: &'static str,
    pub number: &'static str,
    pub name_cannot_be_empty: &'static str,
    pub role_is_required: &'static str,
    pub could_not_create_player: &'static str,
    pub number_must_be_between_0_and_99: &'static str,
    pub role: &'static str,
    pub new_player: &'static str,
    pub error: &'static str,
    pub new_team: &'static str,
    pub year: &'static str,
    pub classification_is_required: &'static str,
    pub could_not_create_team: &'static str,
    pub year_must_be_a_four_digit_number: &'static str,
    pub could_not_load_matches: &'static str,
    pub match_list: &'static str,
    pub could_not_render_match_list: &'static str,
    pub in_progress: &'static str,
    pub could_not_compute_snapshot: &'static str,
    pub team: &'static str,
    pub select: &'static str,
    pub no_matches_yet: &'static str,
    pub no_match_selected: &'static str,
    pub could_not_get_match_status: &'static str,
    pub could_not_add_event: &'static str,
    pub event_is_not_available: &'static str,
    pub no_player_selected: &'static str,
    pub invalid_player_selection: &'static str,
    pub evaluation_not_allowed_for_event: &'static str,
    pub choose_the_event: &'static str,
    pub unknown: &'static str,
    pub choose_the_evaluation: &'static str,
    pub latest_events: &'static str,
    pub player_selection: &'static str,
    pub select_replacement: &'static str,
    pub undo: &'static str,
    pub setter_prefix: &'static str,
    pub us: &'static str,
    pub them: &'static str,
    pub no_available_players: &'static str,
    pub lineup_selection_setter: &'static str,
    pub lineup_selection_libero: &'static str,
    pub serving_team: &'static str,
    pub choose: &'static str,
    pub could_not_load_teams: &'static str,
    pub players: &'static str,
    pub team_not_found: &'static str,
    pub no_players_yet: &'static str,
    pub no_teams_yet: &'static str,
    pub teams: &'static str,
    pub global: &'static str,
    pub faults: &'static str,
    pub errors_report_label: &'static str,
    pub opponent_errors_report_label: &'static str,
    pub counter_attack: &'static str,
    pub distribution: &'static str,
    pub serve: &'static str,
    pub reception: &'static str,
    pub attack: &'static str,
    pub defense: &'static str,
    pub block: &'static str,
    pub fault: &'static str,
    pub opponent_score: &'static str,
    pub opponent_error: &'static str,
    pub substitution: &'static str,
    pub winning_attack: &'static str,
    pub attack_continuation: &'static str,
    pub opponent_counter_attack_opportunity: &'static str,
    pub winning_block: &'static str,
    pub counter_attack_opportunity: &'static str,
    pub limited_attack_options: &'static str,
    pub first_tempo_still_available: &'static str,
    pub few_attack_options_available: &'static str,
    pub ball_goes_straight_over_the_net: &'static str,
    pub opponent_with_limited_attack_options: &'static str,
    pub opponent_with_full_attack_options: &'static str,
    pub ball_goes_straight_back_to_our_court: &'static str,
    pub score: &'static str,
    pub positive: &'static str,
    pub negative: &'static str,
    pub blocked: &'static str,
    pub overpass: &'static str,
    pub ace: &'static str,
    pub subpositive: &'static str,
    pub perfect: &'static str,
    pub net_fault: &'static str,
    pub language_is_required: &'static str,
    pub settings: &'static str,
    pub could_not_load_settings: &'static str,
    pub could_not_save_settings: &'static str,
    pub language: &'static str,
    #[cfg(feature = "self-update")]
    pub updated_to_version: &'static str,
    #[cfg(feature = "self-update")]
    pub update_check_failed: &'static str,
    pub top_international: &'static str,
    pub high_national: &'static str,
    pub national_mid_level: &'static str,
    pub national_low_level: &'static str,
    pub regional: &'static str,
    pub local_division: &'static str,
    pub top_international_description: &'static str,
    pub high_national_description: &'static str,
    pub national_mid_level_description: &'static str,
    pub national_low_level_description: &'static str,
    pub regional_description: &'static str,
    pub local_division_description: &'static str,
    pub men: &'static str,
    pub women: &'static str,
    pub libero: &'static str,
    pub middle_blocker: &'static str,
    pub opposite_hitter: &'static str,
    pub outside_hitter: &'static str,
    pub setter: &'static str,
    pub team_classification: &'static str,
    pub gender: &'static str,
    pub gender_is_required: &'static str,
    pub edit_team: &'static str,
    pub edit_player: &'static str,
}

const EN: Labels = Labels {
    could_not_recognize_home_directory: "could not recognize home directory",
    could_not_create_app_directory: "could not create app directory",
    could_not_create_team_directory: "could not create team directory",
    new_match: "new match",
    navigate: "navigate",
    confirm: "confirm",
    back: "back",
    quit: "quit",
    home: "home",
    opponent: "opponent",
    date: "date",
    opponent_cannot_be_empty: "opponent cannot be empty",
    could_not_create_match: "could not create match",
    invalid_date: "invalid date",
    name: "name",
    number: "number",
    name_cannot_be_empty: "name cannot be empty",
    role_is_required: "role is required",
    could_not_create_player: "could not create player",
    number_must_be_between_0_and_99: "number must be between 0 and 99",
    role: "role",
    new_player: "new player",
    error: "error",
    new_team: "new team",
    year: "year",
    classification_is_required: "classification is required",
    could_not_create_team: "could not create team",
    year_must_be_a_four_digit_number: "year must be a 4-digit number",
    could_not_load_matches: "could not load matches",
    match_list: "match list",
    could_not_render_match_list: "could not render the match list",
    in_progress: "in progress",
    could_not_compute_snapshot: "could not compute the snapshot",
    team: "team",
    select: "select",
    no_matches_yet: "no matches yet",
    no_match_selected: "no match selected",
    could_not_get_match_status: "could not get match status",
    could_not_add_event: "could not add event",
    event_is_not_available: "event {} is not available",
    no_player_selected: "no player selected",
    invalid_player_selection: "invalid player selection",
    evaluation_not_allowed_for_event: "evaluation not allowed for this event {}",
    choose_the_event: "choose the event",
    unknown: "unknown",
    choose_the_evaluation: "choose the evaluation",
    latest_events: "latest events",
    player_selection: "player selection",
    select_replacement: "select replacement",
    undo: "undo",
    setter_prefix: "S",
    us: "us",
    them: "them",
    no_available_players: "no available players",
    lineup_selection_setter: "lineup selection - setter",
    lineup_selection_libero: "lineup selection - libero",
    serving_team: "serving team",
    choose: "choose",
    could_not_load_teams: "could not load teams",
    players: "players",
    team_not_found: "team not found",
    no_players_yet: "no players yet",
    no_teams_yet: "no teams yet",
    teams: "teams",
    global: "global",
    faults: "faults",
    errors_report_label: "err. (unf.)",
    opponent_errors_report_label: "opp. err.",
    counter_attack: "counter attack",
    distribution: "distribution",
    serve: "serve",
    reception: "reception",
    attack: "attack",
    defense: "defense",
    block: "block",
    fault: "fault",
    opponent_score: "opponent score",
    opponent_error: "opponent error",
    substitution: "substitution",
    winning_attack: "winning attack",
    attack_continuation: "attack continuation",
    opponent_counter_attack_opportunity: "opponent counter-attack opportunity",
    winning_block: "winning block",
    counter_attack_opportunity: "counter-attack opportunity",
    limited_attack_options: "limited attack options",
    first_tempo_still_available: "first tempo still available",
    few_attack_options_available: "few attack options available",
    ball_goes_straight_over_the_net: "ball goes straight over the net",
    opponent_with_limited_attack_options: "opponent with limited attack options",
    opponent_with_full_attack_options: "opponent with full attack options",
    ball_goes_straight_back_to_our_court: "ball goes straight back to our court",
    score: "score",
    positive: "positive",
    negative: "negative",
    blocked: "blocked",
    overpass: "overpass",
    ace: "ace",
    subpositive: "subpositive",
    perfect: "perfect",
    net_fault: "net fault",
    language_is_required: "language is required",
    settings: "settings",
    could_not_load_settings: "could not load settings",
    could_not_save_settings: "could not save settings",
    language: "language",
    #[cfg(feature = "self-update")]
    updated_to_version: "updated to version",
    #[cfg(feature = "self-update")]
    update_check_failed: "update check failed",
    top_international: "top international",
    high_national: "high national",
    national_mid_level: "national mid-level",
    national_low_level: "national low-level",
    regional: "regional",
    local_division: "local division",
    top_international_description: "teams competing at the highest international level (continental cups, champions league); fully professional, large budgets, elite staff",
    high_national_description: "teams on top national league",
    national_mid_level_description: "teams competing at national level but not reaching international competitions",
    national_low_level_description: "national teams with limited visibility, often developmental or stepping stones between regional and national levels",
    regional_description: "teams competing at regional level, organized by regional federations; typically amateur or semi-amateur",
    local_division_description: "teams competing at provincial or local level, highly amateur, often community-driven",
    men: "men",
    women: "women",
    libero: "libero",
    middle_blocker: "middle blocker",
    opposite_hitter: "opposite hitter",
    outside_hitter: "outside hitter",
    setter: "setter",
    team_classification: "team classification",
    gender: "gender",
    gender_is_required: "gender is required",
    edit_team: "edit team",
    edit_player: "edit player",
};

const IT: Labels = Labels {
    could_not_recognize_home_directory: "impossibile riconoscere la directory home",
    could_not_create_app_directory: "impossibile creare la directory dell'applicazione",
    could_not_create_team_directory: "impossibile creare la directory della squadra",
    new_match: "nuova partita",
    navigate: "naviga",
    confirm: "conferma",
    back: "indietro",
    quit: "esci",
    home: "in casa",
    opponent: "avversario",
    date: "data",
    opponent_cannot_be_empty: "l'avversario è obbligatorio",
    could_not_create_match: "impossibile creare la partita",
    invalid_date: "data non valida",
    name: "nome",
    number: "numero",
    name_cannot_be_empty: "il nome è obbligatorio",
    role_is_required: "il ruolo è obbligatorio",
    could_not_create_player: "impossibile creare il giocatore",
    number_must_be_between_0_and_99: "il numero deve essere compreso tra 0 e 99",
    role: "ruolo",
    new_player: "nuovo giocatore",
    error: "errore",
    new_team: "nuova squadra",
    year: "anno",
    classification_is_required: "la classificazione è obbligatoria",
    could_not_create_team: "impossibile creare la squadra",
    year_must_be_a_four_digit_number: "l'anno deve essere un numero a 4 cifre",
    could_not_load_matches: "impossibile caricare le partite",
    match_list: "lista partite",
    could_not_render_match_list: "impossibile visualizzare la lista delle partite",
    in_progress: "in corso",
    could_not_compute_snapshot: "impossibile calcolare l'istantanea",
    team: "squadra",
    select: "seleziona",
    no_matches_yet: "nessuna partita al momento",
    no_match_selected: "nessuna partita selezionata",
    could_not_get_match_status: "impossibile ottenere lo stato della partita",
    could_not_add_event: "impossibile aggiungere l'evento",
    event_is_not_available: "l'evento {} non è disponibile",
    no_player_selected: "nessun giocatore selezionato",
    invalid_player_selection: "selezione del giocatore non valida",
    evaluation_not_allowed_for_event: "valutazione non consentita per l'evento {}",
    choose_the_event: "scegli l'evento",
    unknown: "sconosciuto",
    choose_the_evaluation: "scegli la valutazione",
    latest_events: "ultimi eventi",
    player_selection: "selezione giocatore",
    select_replacement: "seleziona sostituto",
    undo: "annulla",
    setter_prefix: "P",
    us: "noi",
    them: "loro",
    no_available_players: "nessun giocatore disponibile",
    lineup_selection_setter: "selezione formazione - palleggiatore",
    lineup_selection_libero: "selezione formazione - libero",
    serving_team: "squadra al servizio",
    choose: "scegli",
    could_not_load_teams: "impossibile caricare le squadre",
    players: "giocatori",
    team_not_found: "squadra non trovata",
    no_players_yet: "nessun giocatore al momento",
    no_teams_yet: "nessuna squadra al momento",
    teams: "squadre",
    global: "globale",
    faults: "falli",
    errors_report_label: "err. (dir.)",
    opponent_errors_report_label: "err. avv.",
    counter_attack: "contrattacco",
    distribution: "distribuzione",
    serve: "battuta",
    reception: "ricezione",
    attack: "attacco",
    defense: "difesa",
    block: "muro",
    fault: "fallo",
    opponent_score: "punto avversario",
    opponent_error: "errore avversario",
    substitution: "sostituzione",
    winning_attack: "attacco vincente",
    attack_continuation: "continuazione attacco",
    opponent_counter_attack_opportunity: "opportunità di contrattacco avversario",
    winning_block: "muro vincente",
    counter_attack_opportunity: "opportunità di contrattacco",
    limited_attack_options: "opzioni di attacco limitate",
    first_tempo_still_available: "primo tempo ancora disponibile",
    few_attack_options_available: "poche opzioni di attacco disponibili",
    ball_goes_straight_over_the_net: "palla che va direttamente oltre la rete",
    opponent_with_limited_attack_options: "avversario con opzioni di attacco limitate",
    opponent_with_full_attack_options: "avversario con opzioni di attacco complete",
    ball_goes_straight_back_to_our_court: "palla che torna direttamente nel nostro campo",
    score: "punto",
    positive: "positivo",
    negative: "negativo",
    blocked: "bloccato",
    overpass: "sopra rete",
    ace: "ace",
    subpositive: "subpositivo",
    perfect: "perfetto",
    net_fault: "fallo di rete",
    language_is_required: "la lingua è obbligatoria",
    settings: "impostazioni",
    could_not_load_settings: "impossibile caricare le impostazioni",
    could_not_save_settings: "impossibile salvare le impostazioni",
    language: "lingua",
    #[cfg(feature = "self-update")]
    updated_to_version: "aggiornato alla versione",
    #[cfg(feature = "self-update")]
    update_check_failed: "impossibile controllare la presenza di aggiornamenti",
    top_international: "top internazionale",
    high_national: "alto nazionale",
    national_mid_level: "nazionale medio",
    national_low_level: "nazionale basso",
    regional: "regionale",
    local_division: "divisione locale",
    top_international_description: "squadre che competono al più alto livello internazionale (coppe continentali, champions league); completamente professionistiche, grandi budget, staff d'élite",
    high_national_description: "squadre nella lega nazionale di vertice",
    national_mid_level_description: "squadre che competono a livello nazionale ma non raggiungono le competizioni internazionali",
    national_low_level_description: "squadre nazionali con visibilità limitata, spesso di sviluppo o trampolini di lancio tra i livelli regionali e nazionali",
    regional_description: "squadre che competono a livello regionale, organizzate dalle federazioni regionali; tipicamente amatoriali o semi-professionistiche",
    local_division_description: "squadre che competono a livello provinciale o locale, altamente amatoriali, spesso guidate dalla comunità",
    men: "maschile",
    women: "femminile",
    libero: "libero",
    middle_blocker: "centrale",
    opposite_hitter: "opposto",
    outside_hitter: "schiacciatore",
    setter: "palleggiatore",
    team_classification: "classificazione della squadra",
    gender: "genere",
    gender_is_required: "il genere è obbligatorio",
    edit_team: "modifica squadra",
    edit_player: "modifica giocatore",
};

static DICTIONARY: Lazy<HashMap<LanguageEnum, &'static Labels>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert(LanguageEnum::En, &EN);
    m.insert(LanguageEnum::It, &IT);
    m
});

static CURRENT_LANGUAGE: OnceCell<RwLock<LanguageEnum>> = OnceCell::new();

/// Default language initialization (should be called once at startup).
pub fn init_language(default: LanguageEnum) {
    CURRENT_LANGUAGE.set(RwLock::new(default)).ok().unwrap();
}

/// Change the current language.
pub fn set_language(lang: LanguageEnum) {
    if let Some(lock) = CURRENT_LANGUAGE.get() {
        *lock.write().unwrap() = lang;
    }
}

/// Returns the labels for the current language.
pub fn current_labels() -> &'static Labels {
    if let Some(lock) = CURRENT_LANGUAGE.get() {
        let lang = *lock.read().unwrap();
        DICTIONARY.get(&lang).unwrap()
    } else {
        &EN
    }
}
