name: CI/CD

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  fmt:
    name: check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo fmt -- --check
  test:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo test --all --all-features
  release:
    name: release
    needs: [fmt, test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - target: aarch64-unknown-linux-gnu
            archive: tar.gz
          - target: x86_64-pc-windows-msvc
            archive: zip
          - target: aarch64-pc-windows-msvc
            archive: zip
          - target: x86_64-apple-darwin
            archive: tar.gz
          - target: aarch64-apple-darwin
            archive: tar.gz
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: build binary
        run: cross build --release --target ${{ matrix.target }}
      - name: package binary
        run: |
          mkdir dist
          BIN_NAME=$(basename $(grep '^name' Cargo.toml | head -n1 | cut -d '"' -f2))
          cd target/${{ matrix.target }}/release
          if [ "${{ matrix.archive }}" = "zip" ]; then
            zip -r ../../../dist/${BIN_NAME}-${{ matrix.target }}.zip $BIN_NAME.exe
          else
            tar czf ../../../dist/${BIN_NAME}-${{ matrix.target }}.tar.gz $BIN_NAME
          fi
      - name: upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
